package pngembed

// WARNING: Auto generated version file. Do not edit this file by hand.
// WARNING: go get github.com/sabhiram/gover to manage this file.
// Version: 0.0.2
const (
	Major = 0
	Minor = 0
	Patch = 2

	Version = "0.0.2"
)
